[package]
name = "quantumfslib"
version = "0.1.0"
authors = ["JosÃ© Molina Colmenero <jmolinacolmenero@gmail.com>"]
edition = "2018"

[dependencies]
ipfsapi = "0.3.0"
web3 = "0.8.0"
regex = "1.2.1"
readonly = "0.1.5"
failure = "0.1.5"
